export const citationRegistry = [
  {
    id: 'internal_disc_11_network_story',
    citationType: 'internal_approved',
    title: 'Fund44 curated network story',
    sourceLabel: 'docs/disclosures.md',
    documentPath: 'docs/disclosures.md',
    reviewedDate: '2026-07-25',
    expiresDate: null,
    approvalStatus: 'business_approved_draft',
    allowedScopes: ['network_story'],
    claimIds: ['F44-MKT-04', 'F44-NET-01', 'F44-TRUST-01'],
  },
  {
    id: 'internal_disc_12_routing_explanation',
    citationType: 'internal_approved',
    title: 'Fund44 fit-over-fees routing explanation',
    sourceLabel: 'docs/disclosures.md',
    documentPath: 'docs/disclosures.md',
    reviewedDate: '2026-07-25',
    expiresDate: null,
    approvalStatus: 'business_approved_draft',
    allowedScopes: ['routing_explanation'],
    claimIds: ['F44-NET-04', 'F44-PROC-06', 'F44-PROC-07'],
  },
  {
    id: 'internal_disc_13_workflow',
    citationType: 'internal_approved',
    title: 'Fund44 faster-process workflow disclosure',
    sourceLabel: 'docs/disclosures.md',
    documentPath: 'docs/disclosures.md',
    reviewedDate: '2026-07-25',
    expiresDate: null,
    approvalStatus: 'business_approved_draft',
    allowedScopes: ['workflow_availability'],
    claimIds: ['F44-NET-03', 'F44-PROC-01', 'F44-PROC-02', 'F44-PROC-04'],
  },
  {
    id: 'internal_disc_03_preview_credit',
    citationType: 'internal_approved',
    title: 'Preview credit-impact disclosure',
    sourceLabel: 'docs/disclosures.md',
    documentPath: 'docs/disclosures.md',
    reviewedDate: '2026-07-25',
    expiresDate: null,
    approvalStatus: 'preview_verified',
    allowedScopes: ['credit_disclosure'],
    claimIds: ['F44-CRED-01'],
  },
  {
    id: 'internal_disc_06_preview_only',
    citationType: 'internal_approved',
    title: 'Preview-only workflow state',
    sourceLabel: 'docs/disclosures.md',
    documentPath: 'docs/disclosures.md',
    reviewedDate: '2026-07-25',
    expiresDate: null,
    approvalStatus: 'preview_verified',
    allowedScopes: ['preview_notice'],
    claimIds: ['F44-PROC-03'],
  },
  {
    id: 'external_sba_loans_overview_2026_07_26',
    citationType: 'external_primary',
    title: 'Loans',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/funding-programs/loans',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    allowedScopes: ['product_overview', 'educational_editorial'],
    claimIds: ['F44-PROD-01', 'F44-PROD-06'],
  },
  {
    id: 'external_sba_7a_loans_2026_07_26',
    citationType: 'external_primary',
    title: '7(a) loans',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/funding-programs/loans/7a-loans',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    allowedScopes: ['product_overview', 'program_detail', 'educational_editorial'],
    claimIds: ['F44-PROD-02', 'F44-PROD-06'],
  },
  {
    id: 'external_sba_504_loans_2026_07_26',
    citationType: 'external_primary',
    title: '504 loans',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/funding-programs/loans/504-loans',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    allowedScopes: ['product_overview', 'program_detail', 'educational_editorial'],
    claimIds: ['F44-PROD-03', 'F44-PROD-06'],
  },
  {
    id: 'external_sba_change_of_ownership_2026_07_26',
    citationType: 'external_primary',
    title: 'Business loan program improvements',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/article/2023/08/10/business-loan-program-improvements',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    allowedScopes: ['product_overview', 'educational_editorial'],
    claimIds: ['F44-PROD-04'],
  },
  {
    id: 'external_sba_buy_existing_business_2026_07_26',
    citationType: 'external_primary',
    title: 'Buy an existing business or franchise',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/business-guide/plan-your-business/buy-existing-business-or-franchise',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    allowedScopes: ['product_overview', 'educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-04', 'F44-PROD-07'],
  },
  {
    id: 'external_wf_businessline_2026_07_26',
    citationType: 'external_reference',
    title: 'BusinessLine line of credit',
    sourceLabel: 'Wells Fargo',
    url: 'https://www.wellsfargo.com/biz/business-credit/lines-of-credit/',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    allowedScopes: ['product_overview', 'educational_editorial'],
    claimIds: ['F44-PROD-05', 'F44-PROD-06'],
  },
  {
    id: 'external_chase_business_loans_2026_07_26',
    citationType: 'external_reference',
    title: 'Business loans & financing',
    sourceLabel: 'Chase for Business',
    url: 'https://www.chase.com/business/loans',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    allowedScopes: ['product_overview', 'educational_editorial'],
    claimIds: ['F44-PROD-05', 'F44-PROD-06'],
  },
  {
    id: 'external_wf_credit_application_2026_07_26',
    citationType: 'external_reference',
    title: 'Developing a good credit application',
    sourceLabel: 'Wells Fargo Small Business Resource Center',
    url: 'https://smallbusinessresources.wf.com/developing-a-good-credit-application/',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    allowedScopes: ['document_guidance', 'educational_editorial'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_wf_prepare_credit_2026_07_26',
    citationType: 'external_reference',
    title: 'Five steps to consider before applying for credit',
    sourceLabel: 'Wells Fargo Small Business Resource Center',
    url: 'https://smallbusinessresources.wf.com/five-steps-to-consider-before-applying-for-credit/',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    allowedScopes: ['document_guidance', 'educational_editorial'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_usbank_equipment_financing_2026_07_26',
    citationType: 'external_reference',
    title: 'Equipment financing and leasing',
    sourceLabel: 'U.S. Bank',
    url: 'https://www.usbank.com/business-banking/business-lending/equipment-finance.html',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    allowedScopes: ['product_overview', 'educational_editorial'],
    claimIds: ['F44-PROD-01', 'F44-PROD-05'],
  },
];

const citationById = new Map(citationRegistry.map((citation) => [citation.id, citation]));

export function getCitationById(id) {
  const citation = citationById.get(id);
  if (!citation) {
    throw new Error(`Unknown citation id: ${id}`);
  }
  return citation;
}

export function getCitationInventory() {
  return citationRegistry.slice();
}
