const INTERNAL_CITATION_FRESHNESS = Object.freeze({
  ownerRole: 'Legal + Content ops',
  reviewerRole: 'Legal',
  ownerState: 'role_assigned_identity_tbd',
  reviewerState: 'role_assigned_identity_tbd',
  reviewWindowDays: 90,
  reviewTriggers: [
    'Monthly governance review cadence',
    'Any approved disclosure wording or claim-register change',
    'Any legal, privacy, consent, or entity-policy change that affects governed copy',
  ],
  staleAction: 'noindex',
  expiredAction: 'block',
});

const EXTERNAL_CITATION_FRESHNESS = Object.freeze({
  ownerRole: 'SEO content',
  reviewerRole: 'Content ops',
  ownerState: 'role_assigned_identity_tbd',
  reviewerState: 'role_assigned_identity_tbd',
  reviewWindowDays: 180,
  reviewTriggers: [
    'Monthly content review cadence',
    'Any product, program, or policy change that affects the cited claim',
    'Any source-page update, redirect, removal, or scope mismatch found during review',
  ],
  staleAction: 'noindex',
  expiredAction: 'block',
});

export const citationRegistry = [
  {
    id: 'internal_disc_11_network_story',
    citationType: 'internal_approved',
    title: 'Fund44 curated network story',
    sourceLabel: 'docs/disclosures.md',
    documentPath: 'docs/disclosures.md',
    reviewedDate: '2026-07-25',
    expiresDate: null,
    approvalStatus: 'business_approved_draft',
    freshness: INTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['network_story'],
    claimIds: ['F44-MKT-04', 'F44-NET-01', 'F44-TRUST-01'],
  },
  {
    id: 'internal_disc_12_routing_explanation',
    citationType: 'internal_approved',
    title: 'Fund44 fit-over-fees routing explanation',
    sourceLabel: 'docs/disclosures.md',
    documentPath: 'docs/disclosures.md',
    reviewedDate: '2026-07-25',
    expiresDate: null,
    approvalStatus: 'business_approved_draft',
    freshness: INTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['routing_explanation'],
    claimIds: ['F44-NET-04', 'F44-PROC-06', 'F44-PROC-07'],
  },
  {
    id: 'internal_disc_13_workflow',
    citationType: 'internal_approved',
    title: 'Fund44 faster-process workflow disclosure',
    sourceLabel: 'docs/disclosures.md',
    documentPath: 'docs/disclosures.md',
    reviewedDate: '2026-07-25',
    expiresDate: null,
    approvalStatus: 'business_approved_draft',
    freshness: INTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['workflow_availability'],
    claimIds: ['F44-NET-03', 'F44-PROC-01', 'F44-PROC-02', 'F44-PROC-04'],
  },
  {
    id: 'internal_disc_03_preview_credit',
    citationType: 'internal_approved',
    title: 'Preview credit-impact disclosure',
    sourceLabel: 'docs/disclosures.md',
    documentPath: 'docs/disclosures.md',
    reviewedDate: '2026-07-25',
    expiresDate: null,
    approvalStatus: 'preview_verified',
    freshness: INTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['credit_disclosure'],
    claimIds: ['F44-CRED-01'],
  },
  {
    id: 'internal_disc_06_preview_only',
    citationType: 'internal_approved',
    title: 'Preview-only workflow state',
    sourceLabel: 'docs/disclosures.md',
    documentPath: 'docs/disclosures.md',
    reviewedDate: '2026-07-25',
    expiresDate: null,
    approvalStatus: 'preview_verified',
    freshness: INTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['preview_notice'],
    claimIds: ['F44-PROC-03'],
  },
  {
    id: 'external_sba_loans_overview_2026_07_26',
    citationType: 'external_primary',
    title: 'Loans',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/funding-programs/loans',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['product_overview', 'educational_editorial'],
    claimIds: ['F44-PROD-01', 'F44-PROD-06'],
  },
  {
    id: 'external_sba_7a_loans_2026_07_26',
    citationType: 'external_primary',
    title: '7(a) loans',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/funding-programs/loans/7a-loans',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['product_overview', 'program_detail', 'educational_editorial'],
    claimIds: ['F44-PROD-02', 'F44-PROD-06'],
  },
  {
    id: 'external_sba_504_loans_2026_07_26',
    citationType: 'external_primary',
    title: '504 loans',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/funding-programs/loans/504-loans',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['product_overview', 'program_detail', 'educational_editorial'],
    claimIds: ['F44-PROD-03', 'F44-PROD-06'],
  },
  {
    id: 'external_sba_change_of_ownership_2026_07_26',
    citationType: 'external_primary',
    title: 'Business loan program improvements',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/article/2023/08/10/business-loan-program-improvements',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['product_overview', 'educational_editorial'],
    claimIds: ['F44-PROD-04'],
  },
  {
    id: 'external_sba_buy_existing_business_2026_07_26',
    citationType: 'external_primary',
    title: 'Buy an existing business or franchise',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/business-guide/plan-your-business/buy-existing-business-or-franchise',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['product_overview', 'educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-04', 'F44-PROD-07'],
  },
  {
    id: 'external_wf_businessline_2026_07_26',
    citationType: 'external_reference',
    title: 'BusinessLine line of credit',
    sourceLabel: 'Wells Fargo',
    url: 'https://www.wellsfargo.com/biz/business-credit/lines-of-credit/',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['product_overview', 'educational_editorial'],
    claimIds: ['F44-PROD-05', 'F44-PROD-06'],
  },
  {
    id: 'external_chase_business_loans_2026_07_26',
    citationType: 'external_reference',
    title: 'Business loans & financing',
    sourceLabel: 'Chase for Business',
    url: 'https://www.chase.com/business/loans',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['product_overview', 'educational_editorial'],
    claimIds: ['F44-PROD-05', 'F44-PROD-06'],
  },
  {
    id: 'external_wf_credit_application_2026_07_26',
    citationType: 'external_reference',
    title: 'Developing a good credit application',
    sourceLabel: 'Wells Fargo Small Business Resource Center',
    url: 'https://smallbusinessresources.wf.com/developing-a-good-credit-application/',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['document_guidance', 'educational_editorial'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_wf_prepare_credit_2026_07_26',
    citationType: 'external_reference',
    title: 'Five steps to consider before applying for credit',
    sourceLabel: 'Wells Fargo Small Business Resource Center',
    url: 'https://smallbusinessresources.wf.com/five-steps-to-consider-before-applying-for-credit/',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['document_guidance', 'educational_editorial'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_usbank_equipment_financing_2026_07_26',
    citationType: 'external_reference',
    title: 'Equipment financing and leasing',
    sourceLabel: 'U.S. Bank',
    url: 'https://www.usbank.com/business-banking/business-lending/equipment-finance.html',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['product_overview', 'educational_editorial'],
    claimIds: ['F44-PROD-01', 'F44-PROD-05'],
  },
  {
    id: 'external_ftc_franchise_rule_2026_07_26',
    citationType: 'external_primary',
    title: 'Franchise Rule',
    sourceLabel: 'Federal Trade Commission',
    url: 'https://www.ftc.gov/legal-library/browse/rules/franchise-rule',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-04', 'F44-PROD-07'],
  },
  {
    id: 'external_sba_franchise_directory_2026_07_26',
    citationType: 'external_primary',
    title: 'SBA Franchise Directory',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/document/support-sba-franchise-directory',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-04', 'F44-PROD-07'],
  },
  {
    id: 'external_fmcsa_usdot_number_2026_07_26',
    citationType: 'external_primary',
    title: 'Do I Need a USDOT Number?',
    sourceLabel: 'Federal Motor Carrier Safety Administration',
    url: 'https://www.fmcsa.dot.gov/registration/do-i-need-usdot-number',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-01', 'F44-PROD-07'],
  },
  {
    id: 'external_fmcsa_operating_authority_2026_07_26',
    citationType: 'external_primary',
    title: 'Get Operating Authority (Docket Number)',
    sourceLabel: 'Federal Motor Carrier Safety Administration',
    url: 'https://www.fmcsa.dot.gov/registration/get-mc-number-authority-operate',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-01', 'F44-PROD-07'],
  },
  {
    id: 'external_fmcsa_boc3_2026_07_26',
    citationType: 'external_primary',
    title: 'Form BOC-3 - Designation of Agents for Service of Process',
    sourceLabel: 'Federal Motor Carrier Safety Administration',
    url: 'https://www.fmcsa.dot.gov/registration/form-boc-3-designation-agents-service-process',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-01', 'F44-PROD-07'],
  },
  {
    id: 'external_fmcsa_insurance_filing_2026_07_26',
    citationType: 'external_primary',
    title: 'Insurance Filing Requirements',
    sourceLabel: 'Federal Motor Carrier Safety Administration',
    url: 'https://www.fmcsa.dot.gov/registration/insurance-filing-requirements',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-01', 'F44-PROD-07'],
  },
  {
    id: 'external_irs_form_2290_2026_07_26',
    citationType: 'external_primary',
    title: 'About Form 2290, Heavy Highway Vehicle Use Tax Return',
    sourceLabel: 'Internal Revenue Service',
    url: 'https://www.irs.gov/forms-pubs/about-form-2290',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-01', 'F44-PROD-07'],
  },
  {
    id: 'external_irs_trucking_tax_center_2026_07_26',
    citationType: 'external_primary',
    title: 'Trucking tax center',
    sourceLabel: 'Internal Revenue Service',
    url: 'https://www.irs.gov/businesses/small-businesses-self-employed/trucking-tax-center',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-01', 'F44-PROD-07'],
  },
  {
    id: 'external_sba_surety_bonds_2026_07_26',
    citationType: 'external_primary',
    title: 'Surety bonds',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/funding-programs/surety-bonds',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['product_overview', 'educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-05', 'F44-PROD-07'],
  },
  {
    id: 'external_sba_wip_form_994f_2026_07_26',
    citationType: 'external_primary',
    title: 'Schedule of Work in Process',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/document/sba-form-994f-schedule-work-process',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_sba_7a_wcp_2026_07_26',
    citationType: 'external_primary',
    title: '7(a) Working Capital Pilot program',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/partners/lenders/7a-loan-program/7a-working-capital-pilot-program',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['product_overview', 'program_detail', 'educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-05', 'F44-PROD-07'],
  },
  {
    id: 'external_sba_san_francisco_district_2026_07_26',
    citationType: 'external_primary',
    title: 'San Francisco District',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/district/san-francisco',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_sba_sacramento_district_2026_07_26',
    citationType: 'external_primary',
    title: 'Sacramento District',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/district/sacramento',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_sba_fresno_district_2026_07_26',
    citationType: 'external_primary',
    title: 'Fresno District',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/district/fresno',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_sba_los_angeles_district_2026_07_26',
    citationType: 'external_primary',
    title: 'Los Angeles District',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/district/los-angeles',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_sba_orange_county_inland_empire_district_2026_07_26',
    citationType: 'external_primary',
    title: 'Orange County / Inland Empire District',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/district/orange-county-inland-empire',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_sba_san_diego_district_2026_07_26',
    citationType: 'external_primary',
    title: 'San Diego District',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/district/san-diego',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_california_sbdc_2026_07_26',
    citationType: 'external_primary',
    title: 'California SBDC',
    sourceLabel: 'California SBDC',
    url: 'https://www.californiasbdc.org/',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_california_sbdc_find_2026_07_26',
    citationType: 'external_primary',
    title: 'Find My SBDC',
    sourceLabel: 'California SBDC',
    url: 'https://www.californiasbdc.org/find-your-sbdc/',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_calosba_resources_2026_07_26',
    citationType: 'external_primary',
    title: 'Funding opportunities for small businesses and nonprofits',
    sourceLabel: 'California Office of the Small Business Advocate',
    url: 'https://calosba.ca.gov/for-small-businesses-and-non-profits/funding-opportunities-for-small-businesses-and-nonprofits/',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_sba_north_florida_district_2026_07_26',
    citationType: 'external_primary',
    title: 'North Florida District',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/district/north-florida',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_sba_south_florida_district_2026_07_26',
    citationType: 'external_primary',
    title: 'South Florida District',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/district/south-florida',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_florida_sbdc_2026_07_26',
    citationType: 'external_primary',
    title: 'Florida SBDC',
    sourceLabel: 'Florida SBDC',
    url: 'https://floridasbdc.org/',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_florida_sbdc_find_2026_07_26',
    citationType: 'external_primary',
    title: 'Find Your SBDC',
    sourceLabel: 'Florida SBDC',
    url: 'https://floridasbdc.org/find/',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_florida_small_business_2026_07_26',
    citationType: 'external_primary',
    title: 'Small Business',
    sourceLabel: 'FloridaCommerce',
    url: 'https://www.floridajobs.org/small-business',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_sba_buffalo_district_2026_07_26',
    citationType: 'external_primary',
    title: 'Buffalo District',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/district/buffalo',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_sba_syracuse_district_2026_07_26',
    citationType: 'external_primary',
    title: 'Syracuse District',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/district/syracuse',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_sba_metro_new_york_district_2026_07_26',
    citationType: 'external_primary',
    title: 'Metro New York District',
    sourceLabel: 'U.S. Small Business Administration',
    url: 'https://www.sba.gov/district/metro-new-york',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_nysbdc_regional_centers_2026_07_26',
    citationType: 'external_primary',
    title: 'Regional Centers',
    sourceLabel: 'New York Small Business Development Centers',
    url: 'https://nysbdc.org/regional-centers/',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
  {
    id: 'external_ny_start_business_2026_07_26',
    citationType: 'external_primary',
    title: 'Start a Business in New York State',
    sourceLabel: 'The State of New York',
    url: 'https://www.ny.gov/services/start-business-new-york-state',
    reviewedDate: '2026-07-26',
    expiresDate: '2027-07-26',
    approvalStatus: 'current_reviewed',
    freshness: EXTERNAL_CITATION_FRESHNESS,
    allowedScopes: ['educational_editorial', 'document_guidance'],
    claimIds: ['F44-PROD-07'],
  },
];

const citationById = new Map(citationRegistry.map((citation) => [citation.id, citation]));

export function getCitationById(id) {
  const citation = citationById.get(id);
  if (!citation) {
    throw new Error(`Unknown citation id: ${id}`);
  }
  return citation;
}

export function getCitationInventory() {
  return citationRegistry.slice();
}
