export const routeManifest = {
  site: {
    siteName: 'Fund44',
    baseUrl: 'https://fund44.com',
  },
  routes: [
    {
      routeId: 'home',
      analyticsRouteId: 'home',
      pageKey: 'home',
      path: '/',
      pageType: 'home',
      templateId: 'home_page',
      routeFamily: 'home',
      contentId: 'page_home',
      title: 'Home',
      breadcrumbLabel: 'Home',
      footerLabel: 'Home',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'weekly', priority: '1.0' },
      legacyHashes: ['#/'],
    },
    {
      routeId: 'financing',
      analyticsRouteId: 'financing',
      pageKey: 'financing',
      path: '/financing',
      pageType: 'financing_hub',
      templateId: 'financing_hub',
      routeFamily: 'financing_hub',
      contentId: 'page_financing',
      title: 'Financing overview',
      navLabel: 'Financing',
      breadcrumbLabel: 'Financing',
      footerLabel: 'All financing',
      panelLabel: 'Financing overview',
      panelDescription: 'All the paths in one place',
      parentRouteId: 'home',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.9' },
      legacyHashes: ['#/financing'],
    },
    {
      routeId: 'sba_7a',
      analyticsRouteId: 'sba_7a',
      pageKey: 'sba7a',
      path: '/sba-7a',
      pageType: 'program_page',
      templateId: 'product_page',
      routeFamily: 'financing_program',
      contentId: 'page_sba_7a',
      title: 'SBA 7(a) loans',
      breadcrumbLabel: 'SBA 7(a)',
      footerLabel: 'SBA 7(a) loans',
      panelLabel: 'SBA 7(a) loans',
      panelDescription: 'Flexible, longer-term capital',
      parentRouteId: 'financing',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.8' },
      legacyHashes: ['#/sba-7a'],
    },
    {
      routeId: 'sba_504',
      analyticsRouteId: 'sba_504',
      pageKey: 'sba504',
      path: '/sba-504',
      pageType: 'program_page',
      templateId: 'product_page',
      routeFamily: 'financing_program',
      contentId: 'page_sba_504',
      title: 'SBA 504 loans',
      breadcrumbLabel: 'SBA 504',
      footerLabel: 'SBA 504 loans',
      panelLabel: 'SBA 504 loans',
      panelDescription: 'Real estate & major equipment',
      parentRouteId: 'financing',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.8' },
      legacyHashes: ['#/sba-504'],
    },
    {
      routeId: 'business_acquisition',
      analyticsRouteId: 'business_acquisition',
      pageKey: 'acquisition',
      path: '/business-acquisition',
      pageType: 'program_page',
      templateId: 'product_page',
      routeFamily: 'financing_program',
      contentId: 'page_business_acquisition',
      title: 'Business acquisition',
      breadcrumbLabel: 'Business acquisition',
      footerLabel: 'Business acquisition',
      panelLabel: 'Business acquisition',
      panelDescription: 'Buy a business or partner out',
      parentRouteId: 'financing',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.8' },
      legacyHashes: ['#/business-acquisition'],
    },
    {
      routeId: 'working_capital',
      analyticsRouteId: 'working_capital',
      pageKey: 'workingCapital',
      path: '/working-capital',
      pageType: 'program_page',
      templateId: 'product_page',
      routeFamily: 'financing_program',
      contentId: 'page_working_capital',
      title: 'Working capital & lines of credit',
      breadcrumbLabel: 'Working capital',
      footerLabel: 'Working capital & lines',
      panelLabel: 'Working capital & lines',
      panelDescription: 'Day-to-day cash flow',
      parentRouteId: 'financing',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.8' },
      legacyHashes: ['#/working-capital'],
    },
    {
      routeId: 'term_loan',
      analyticsRouteId: 'term_loan',
      pageKey: 'termLoan',
      path: '/term-loan',
      pageType: 'program_page',
      templateId: 'product_page',
      routeFamily: 'financing_program',
      contentId: 'page_term_loan',
      title: 'Business term loans',
      breadcrumbLabel: 'Term loan',
      footerLabel: 'Business term loans',
      panelLabel: 'Business term loans',
      panelDescription: 'One-time projects and planned growth',
      parentRouteId: 'financing',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.8' },
      legacyHashes: ['#/term-loan'],
    },
    {
      routeId: 'line_of_credit',
      analyticsRouteId: 'line_of_credit',
      pageKey: 'lineOfCredit',
      path: '/line-of-credit',
      pageType: 'program_page',
      templateId: 'product_page',
      routeFamily: 'financing_program',
      contentId: 'page_line_of_credit',
      title: 'Business lines of credit',
      breadcrumbLabel: 'Line of credit',
      footerLabel: 'Business lines of credit',
      panelLabel: 'Business lines of credit',
      panelDescription: 'Recurring cash-flow flexibility',
      parentRouteId: 'financing',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.8' },
      legacyHashes: ['#/line-of-credit'],
    },
    {
      routeId: 'equipment_financing',
      analyticsRouteId: 'equipment_financing',
      pageKey: 'equipmentFinancing',
      path: '/equipment-financing',
      pageType: 'program_page',
      templateId: 'product_page',
      routeFamily: 'financing_program',
      contentId: 'page_equipment_financing',
      title: 'Equipment financing',
      breadcrumbLabel: 'Equipment financing',
      footerLabel: 'Equipment financing',
      panelLabel: 'Equipment financing',
      panelDescription: 'Asset-backed equipment purchases',
      parentRouteId: 'financing',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.8' },
      legacyHashes: ['#/equipment-financing'],
    },
    {
      routeId: 'buy_a_business',
      analyticsRouteId: 'buy_a_business',
      pageKey: 'buyBusinessUseCase',
      path: '/use-cases/buy-a-business',
      pageType: 'use_case',
      templateId: 'use_case_page',
      routeFamily: 'use_case',
      contentId: 'use_case_buy_a_business',
      title: 'Buy a business',
      breadcrumbLabel: 'Buy a business',
      footerLabel: 'Buy a business',
      panelLabel: 'Buy a business',
      panelDescription: 'Acquisition and ownership-transition paths',
      parentRouteId: 'financing',
      slug: 'buy-a-business',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/use-cases/buy-a-business'],
    },
    {
      routeId: 'owner_occupied_real_estate',
      analyticsRouteId: 'owner_occupied_real_estate',
      pageKey: 'ownerOccupiedRealEstateUseCase',
      path: '/use-cases/owner-occupied-real-estate',
      pageType: 'use_case',
      templateId: 'use_case_page',
      routeFamily: 'use_case',
      contentId: 'use_case_owner_occupied_real_estate',
      title: 'Owner-occupied real estate',
      breadcrumbLabel: 'Owner-occupied real estate',
      footerLabel: 'Owner-occupied real estate',
      panelLabel: 'Owner-occupied real estate',
      panelDescription: 'Property purchase, build, or refinance',
      parentRouteId: 'financing',
      slug: 'owner-occupied-real-estate',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/use-cases/owner-occupied-real-estate'],
    },
    {
      routeId: 'cash_flow_needs',
      analyticsRouteId: 'cash_flow_needs',
      pageKey: 'cashFlowNeedsUseCase',
      path: '/use-cases/cash-flow-needs',
      pageType: 'use_case',
      templateId: 'use_case_page',
      routeFamily: 'use_case',
      contentId: 'use_case_cash_flow_needs',
      title: 'Cash-flow needs',
      breadcrumbLabel: 'Cash-flow needs',
      footerLabel: 'Cash-flow needs',
      panelLabel: 'Cash-flow needs',
      panelDescription: 'Recurring operating and working-capital gaps',
      parentRouteId: 'financing',
      slug: 'cash-flow-needs',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/use-cases/cash-flow-needs'],
    },
    {
      routeId: 'equipment_purchase',
      analyticsRouteId: 'equipment_purchase',
      pageKey: 'equipmentPurchaseUseCase',
      path: '/use-cases/equipment-purchase',
      pageType: 'use_case',
      templateId: 'use_case_page',
      routeFamily: 'use_case',
      contentId: 'use_case_equipment_purchase',
      title: 'Equipment purchase',
      breadcrumbLabel: 'Equipment purchase',
      footerLabel: 'Equipment purchase',
      panelLabel: 'Equipment purchase',
      panelDescription: 'Machinery, vehicles, and asset financing',
      parentRouteId: 'financing',
      slug: 'equipment-purchase',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/use-cases/equipment-purchase'],
    },
    {
      routeId: 'business_expansion',
      analyticsRouteId: 'business_expansion',
      pageKey: 'businessExpansionUseCase',
      path: '/use-cases/business-expansion',
      pageType: 'use_case',
      templateId: 'use_case_page',
      routeFamily: 'use_case',
      contentId: 'use_case_business_expansion',
      title: 'Business expansion',
      breadcrumbLabel: 'Business expansion',
      footerLabel: 'Business expansion',
      panelLabel: 'Business expansion',
      panelDescription: 'Growth projects, new locations, and scale-up plans',
      parentRouteId: 'financing',
      slug: 'business-expansion',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/use-cases/business-expansion'],
    },
    {
      routeId: 'refinance_business_debt',
      analyticsRouteId: 'refinance_business_debt',
      pageKey: 'refinanceBusinessDebtUseCase',
      path: '/use-cases/refinance-business-debt',
      pageType: 'use_case',
      templateId: 'use_case_page',
      routeFamily: 'use_case',
      contentId: 'use_case_refinance_business_debt',
      title: 'Refinance business debt',
      breadcrumbLabel: 'Refinance business debt',
      footerLabel: 'Refinance business debt',
      panelLabel: 'Refinance business debt',
      panelDescription: 'Refinancing and restructuring existing obligations',
      parentRouteId: 'financing',
      slug: 'refinance-business-debt',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/use-cases/refinance-business-debt'],
    },
    {
      routeId: 'how_it_works',
      analyticsRouteId: 'how_it_works',
      pageKey: 'howItWorks',
      path: '/how-it-works',
      pageType: 'financing_hub',
      templateId: 'process_page',
      routeFamily: 'conversion_support',
      contentId: 'page_how_it_works',
      title: 'How it works',
      navLabel: 'How it works',
      breadcrumbLabel: 'How it works',
      footerLabel: 'How it works',
      parentRouteId: 'home',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/how-it-works'],
    },
    {
      routeId: 'about',
      analyticsRouteId: 'about',
      pageKey: 'about',
      path: '/about',
      pageType: 'financing_hub',
      templateId: 'brand_page',
      routeFamily: 'brand',
      contentId: 'page_about',
      title: 'About Fund44',
      navLabel: 'About',
      breadcrumbLabel: 'About',
      footerLabel: 'About Fund44',
      parentRouteId: 'home',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: false, changefreq: 'monthly', priority: '0.6' },
      legacyHashes: ['#/about'],
    },
    {
      routeId: 'resources',
      analyticsRouteId: 'resources',
      pageKey: 'resources',
      path: '/resources',
      pageType: 'article',
      templateId: 'resources_hub',
      routeFamily: 'resources_hub',
      contentId: 'page_resources',
      title: 'Resources',
      navLabel: 'Resources',
      breadcrumbLabel: 'Resources',
      footerLabel: 'Learning hub',
      parentRouteId: 'home',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'weekly', priority: '0.7' },
      legacyHashes: ['#/resources'],
    },
    {
      routeId: 'resource_sba_7a_vs_504',
      analyticsRouteId: 'resource_sba_7a_vs_504',
      pageKey: 'article',
      path: '/resources/sba-7a-vs-504',
      pageType: 'article',
      templateId: 'editorial_article',
      routeFamily: 'resources_article',
      contentId: 'article_sba_7a_vs_504',
      title: 'SBA 7(a) vs SBA 504',
      breadcrumbLabel: 'SBA 7(a) vs 504',
      footerLabel: 'SBA 7(a) vs 504',
      parentRouteId: 'resources',
      slug: 'sba-7a-vs-504',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: false, landing: true, changefreq: 'monthly', priority: '0.6' },
      legacyHashes: ['#/resources/sba-7a-vs-504'],
    },
    {
      routeId: 'resource_preparing_documents',
      analyticsRouteId: 'resource_preparing_documents',
      pageKey: 'article',
      path: '/resources/preparing-your-documents',
      pageType: 'article',
      templateId: 'editorial_article',
      routeFamily: 'resources_article',
      contentId: 'article_preparing_your_documents',
      title: 'Preparing your documents',
      breadcrumbLabel: 'Preparing your documents',
      parentRouteId: 'resources',
      slug: 'preparing-your-documents',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: false, landing: true, changefreq: 'monthly', priority: '0.6' },
      legacyHashes: ['#/resources/preparing-your-documents'],
    },
    {
      routeId: 'resource_working_capital_vs_term_loan',
      analyticsRouteId: 'resource_working_capital_vs_term_loan',
      pageKey: 'article',
      path: '/resources/working-capital-vs-term-loan',
      pageType: 'article',
      templateId: 'editorial_article',
      routeFamily: 'resources_article',
      contentId: 'article_working_capital_vs_term_loan',
      title: 'Line of credit or term loan?',
      breadcrumbLabel: 'Line of credit or term loan?',
      parentRouteId: 'resources',
      slug: 'working-capital-vs-term-loan',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: false, landing: true, changefreq: 'monthly', priority: '0.6' },
      legacyHashes: ['#/resources/working-capital-vs-term-loan'],
    },
    {
      routeId: 'privacy',
      analyticsRouteId: 'privacy',
      pageKey: 'privacy',
      path: '/privacy',
      pageType: 'legal',
      templateId: 'legal_page',
      routeFamily: 'legal',
      contentId: 'page_privacy',
      title: 'Privacy',
      breadcrumbLabel: 'Privacy',
      footerLabel: 'Privacy',
      parentRouteId: 'home',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: false, changefreq: 'yearly', priority: '0.3' },
      legacyHashes: ['#/privacy'],
    },
    {
      routeId: 'terms',
      analyticsRouteId: 'terms',
      pageKey: 'terms',
      path: '/terms',
      pageType: 'legal',
      templateId: 'legal_page',
      routeFamily: 'legal',
      contentId: 'page_terms',
      title: 'Terms & disclosures',
      breadcrumbLabel: 'Terms & disclosures',
      footerLabel: 'Terms & disclosures',
      parentRouteId: 'home',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: false, changefreq: 'yearly', priority: '0.3' },
      legacyHashes: ['#/terms'],
    },
    {
      routeId: 'contact',
      analyticsRouteId: 'contact',
      pageKey: 'contact',
      path: '/contact',
      pageType: 'contact',
      templateId: 'contact_page',
      routeFamily: 'contact',
      contentId: 'page_contact',
      title: 'Contact',
      breadcrumbLabel: 'Contact',
      footerLabel: 'Contact',
      parentRouteId: 'home',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: false, changefreq: 'yearly', priority: '0.3' },
      legacyHashes: ['#/contact'],
    },
    {
      routeId: 'not_found',
      analyticsRouteId: 'not_found',
      pageKey: 'notFound',
      path: '/404',
      pageType: '404',
      templateId: '404_page',
      routeFamily: 'error',
      contentId: 'page_404',
      title: 'Page not found',
      breadcrumbLabel: 'Not found',
      crawl: { canonical: false, indexable: false, sitemap: false, llms: false, landing: false, changefreq: 'never', priority: '0.0' },
      legacyHashes: [],
    },
  ],
  navigation: {
    primary: [
      {
        routeId: 'financing',
        label: 'Financing',
        panel: ['financing', 'sba_7a', 'sba_504', 'business_acquisition', 'working_capital', 'term_loan', 'line_of_credit', 'equipment_financing', 'buy_a_business', 'owner_occupied_real_estate', 'cash_flow_needs', 'equipment_purchase', 'business_expansion', 'refinance_business_debt'],
      },
      { routeId: 'how_it_works', label: 'How it works' },
      { routeId: 'resources', label: 'Resources' },
      { routeId: 'about', label: 'About' },
    ],
    mobile: [
      { routeId: 'home', label: 'Home' },
      { routeId: 'financing', label: 'Financing' },
      { routeId: 'sba_7a', label: 'SBA 7(a) loans', className: 'sub' },
      { routeId: 'sba_504', label: 'SBA 504 loans', className: 'sub' },
      { routeId: 'business_acquisition', label: 'Business acquisition', className: 'sub' },
      { routeId: 'working_capital', label: 'Working capital & lines', className: 'sub' },
      { routeId: 'term_loan', label: 'Business term loans', className: 'sub' },
      { routeId: 'line_of_credit', label: 'Business lines of credit', className: 'sub' },
      { routeId: 'equipment_financing', label: 'Equipment financing', className: 'sub' },
      { routeId: 'buy_a_business', label: 'Buy a business', className: 'sub' },
      { routeId: 'owner_occupied_real_estate', label: 'Owner-occupied real estate', className: 'sub' },
      { routeId: 'cash_flow_needs', label: 'Cash-flow needs', className: 'sub' },
      { routeId: 'equipment_purchase', label: 'Equipment purchase', className: 'sub' },
      { routeId: 'business_expansion', label: 'Business expansion', className: 'sub' },
      { routeId: 'refinance_business_debt', label: 'Refinance business debt', className: 'sub' },
      { routeId: 'how_it_works', label: 'How it works' },
      { routeId: 'resources', label: 'Resources' },
      { routeId: 'about', label: 'About' },
    ],
    footer: [
      { heading: 'Financing', items: ['sba_7a', 'sba_504', 'business_acquisition', 'working_capital', 'term_loan', 'line_of_credit', 'equipment_financing', 'buy_a_business', 'owner_occupied_real_estate', 'cash_flow_needs', 'equipment_purchase', 'business_expansion', 'refinance_business_debt', 'financing'] },
      { heading: 'Company', items: ['how_it_works', 'about', 'resources', 'resource_sba_7a_vs_504'] },
      { heading: 'Legal', items: ['privacy', 'terms', 'contact'] },
    ],
  },
  ctaDestinations: {
    explore_financing: { routeId: 'financing' },
    learn_how_it_works: { routeId: 'how_it_works' },
    back_home: { routeId: 'home' },
  },
};
