export const routeManifest = {
  site: {
    siteName: 'Fund44',
    baseUrl: 'https://fund44.com',
  },
  routes: [
    {
      routeId: 'home',
      analyticsRouteId: 'home',
      pageKey: 'home',
      path: '/',
      pageType: 'home',
      templateId: 'home_page',
      routeFamily: 'home',
      contentId: 'page_home',
      title: 'Home',
      breadcrumbLabel: 'Home',
      footerLabel: 'Home',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'weekly', priority: '1.0' },
      legacyHashes: ['#/'],
    },
    {
      routeId: 'financing',
      analyticsRouteId: 'financing',
      pageKey: 'financing',
      path: '/financing',
      pageType: 'financing_hub',
      templateId: 'financing_hub',
      routeFamily: 'financing_hub',
      contentId: 'page_financing',
      title: 'Financing overview',
      navLabel: 'Financing',
      breadcrumbLabel: 'Financing',
      footerLabel: 'All financing',
      panelLabel: 'Financing overview',
      panelDescription: 'All the paths in one place',
      parentRouteId: 'home',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.9' },
      legacyHashes: ['#/financing'],
    },
    {
      routeId: 'sba_7a',
      analyticsRouteId: 'sba_7a',
      pageKey: 'sba7a',
      path: '/sba-7a',
      pageType: 'program_page',
      templateId: 'product_page',
      routeFamily: 'financing_program',
      contentId: 'page_sba_7a',
      title: 'SBA 7(a) loans',
      breadcrumbLabel: 'SBA 7(a)',
      footerLabel: 'SBA 7(a) loans',
      panelLabel: 'SBA 7(a) loans',
      panelDescription: 'Flexible, longer-term capital',
      parentRouteId: 'financing',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.8' },
      legacyHashes: ['#/sba-7a'],
    },
    {
      routeId: 'sba_504',
      analyticsRouteId: 'sba_504',
      pageKey: 'sba504',
      path: '/sba-504',
      pageType: 'program_page',
      templateId: 'product_page',
      routeFamily: 'financing_program',
      contentId: 'page_sba_504',
      title: 'SBA 504 loans',
      breadcrumbLabel: 'SBA 504',
      footerLabel: 'SBA 504 loans',
      panelLabel: 'SBA 504 loans',
      panelDescription: 'Real estate & major equipment',
      parentRouteId: 'financing',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.8' },
      legacyHashes: ['#/sba-504'],
    },
    {
      routeId: 'business_acquisition',
      analyticsRouteId: 'business_acquisition',
      pageKey: 'acquisition',
      path: '/business-acquisition',
      pageType: 'program_page',
      templateId: 'product_page',
      routeFamily: 'financing_program',
      contentId: 'page_business_acquisition',
      title: 'Business acquisition',
      breadcrumbLabel: 'Business acquisition',
      footerLabel: 'Business acquisition',
      panelLabel: 'Business acquisition',
      panelDescription: 'Buy a business or partner out',
      parentRouteId: 'financing',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.8' },
      legacyHashes: ['#/business-acquisition'],
    },
    {
      routeId: 'working_capital',
      analyticsRouteId: 'working_capital',
      pageKey: 'workingCapital',
      path: '/working-capital',
      pageType: 'program_page',
      templateId: 'product_page',
      routeFamily: 'financing_program',
      contentId: 'page_working_capital',
      title: 'Working capital & lines of credit',
      breadcrumbLabel: 'Working capital',
      footerLabel: 'Working capital & lines',
      panelLabel: 'Working capital & lines',
      panelDescription: 'Day-to-day cash flow',
      parentRouteId: 'financing',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.8' },
      legacyHashes: ['#/working-capital'],
    },
    {
      routeId: 'term_loan',
      analyticsRouteId: 'term_loan',
      pageKey: 'termLoan',
      path: '/term-loan',
      pageType: 'program_page',
      templateId: 'product_page',
      routeFamily: 'financing_program',
      contentId: 'page_term_loan',
      title: 'Business term loans',
      breadcrumbLabel: 'Term loan',
      footerLabel: 'Business term loans',
      panelLabel: 'Business term loans',
      panelDescription: 'One-time projects and planned growth',
      parentRouteId: 'financing',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.8' },
      legacyHashes: ['#/term-loan'],
    },
    {
      routeId: 'line_of_credit',
      analyticsRouteId: 'line_of_credit',
      pageKey: 'lineOfCredit',
      path: '/line-of-credit',
      pageType: 'program_page',
      templateId: 'product_page',
      routeFamily: 'financing_program',
      contentId: 'page_line_of_credit',
      title: 'Business lines of credit',
      breadcrumbLabel: 'Line of credit',
      footerLabel: 'Business lines of credit',
      panelLabel: 'Business lines of credit',
      panelDescription: 'Recurring cash-flow flexibility',
      parentRouteId: 'financing',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.8' },
      legacyHashes: ['#/line-of-credit'],
    },
    {
      routeId: 'equipment_financing',
      analyticsRouteId: 'equipment_financing',
      pageKey: 'equipmentFinancing',
      path: '/equipment-financing',
      pageType: 'program_page',
      templateId: 'product_page',
      routeFamily: 'financing_program',
      contentId: 'page_equipment_financing',
      title: 'Equipment financing',
      breadcrumbLabel: 'Equipment financing',
      footerLabel: 'Equipment financing',
      panelLabel: 'Equipment financing',
      panelDescription: 'Asset-backed equipment purchases',
      parentRouteId: 'financing',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.8' },
      legacyHashes: ['#/equipment-financing'],
    },
    {
      routeId: 'buy_a_business',
      analyticsRouteId: 'buy_a_business',
      pageKey: 'buyBusinessUseCase',
      path: '/use-cases/buy-a-business',
      pageType: 'use_case',
      templateId: 'use_case_page',
      routeFamily: 'use_case',
      contentId: 'use_case_buy_a_business',
      title: 'Buy a business',
      breadcrumbLabel: 'Buy a business',
      footerLabel: 'Buy a business',
      panelLabel: 'Buy a business',
      panelDescription: 'Acquisition and ownership-transition paths',
      parentRouteId: 'financing',
      slug: 'buy-a-business',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/use-cases/buy-a-business'],
    },
    {
      routeId: 'owner_occupied_real_estate',
      analyticsRouteId: 'owner_occupied_real_estate',
      pageKey: 'ownerOccupiedRealEstateUseCase',
      path: '/use-cases/owner-occupied-real-estate',
      pageType: 'use_case',
      templateId: 'use_case_page',
      routeFamily: 'use_case',
      contentId: 'use_case_owner_occupied_real_estate',
      title: 'Owner-occupied real estate',
      breadcrumbLabel: 'Owner-occupied real estate',
      footerLabel: 'Owner-occupied real estate',
      panelLabel: 'Owner-occupied real estate',
      panelDescription: 'Property purchase, build, or refinance',
      parentRouteId: 'financing',
      slug: 'owner-occupied-real-estate',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/use-cases/owner-occupied-real-estate'],
    },
    {
      routeId: 'cash_flow_needs',
      analyticsRouteId: 'cash_flow_needs',
      pageKey: 'cashFlowNeedsUseCase',
      path: '/use-cases/cash-flow-needs',
      pageType: 'use_case',
      templateId: 'use_case_page',
      routeFamily: 'use_case',
      contentId: 'use_case_cash_flow_needs',
      title: 'Cash-flow needs',
      breadcrumbLabel: 'Cash-flow needs',
      footerLabel: 'Cash-flow needs',
      panelLabel: 'Cash-flow needs',
      panelDescription: 'Recurring operating and working-capital gaps',
      parentRouteId: 'financing',
      slug: 'cash-flow-needs',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/use-cases/cash-flow-needs'],
    },
    {
      routeId: 'equipment_purchase',
      analyticsRouteId: 'equipment_purchase',
      pageKey: 'equipmentPurchaseUseCase',
      path: '/use-cases/equipment-purchase',
      pageType: 'use_case',
      templateId: 'use_case_page',
      routeFamily: 'use_case',
      contentId: 'use_case_equipment_purchase',
      title: 'Equipment purchase',
      breadcrumbLabel: 'Equipment purchase',
      footerLabel: 'Equipment purchase',
      panelLabel: 'Equipment purchase',
      panelDescription: 'Machinery, vehicles, and asset financing',
      parentRouteId: 'financing',
      slug: 'equipment-purchase',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/use-cases/equipment-purchase'],
    },
    {
      routeId: 'business_expansion',
      analyticsRouteId: 'business_expansion',
      pageKey: 'businessExpansionUseCase',
      path: '/use-cases/business-expansion',
      pageType: 'use_case',
      templateId: 'use_case_page',
      routeFamily: 'use_case',
      contentId: 'use_case_business_expansion',
      title: 'Business expansion',
      breadcrumbLabel: 'Business expansion',
      footerLabel: 'Business expansion',
      panelLabel: 'Business expansion',
      panelDescription: 'Growth projects, new locations, and scale-up plans',
      parentRouteId: 'financing',
      slug: 'business-expansion',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/use-cases/business-expansion'],
    },
    {
      routeId: 'refinance_business_debt',
      analyticsRouteId: 'refinance_business_debt',
      pageKey: 'refinanceBusinessDebtUseCase',
      path: '/use-cases/refinance-business-debt',
      pageType: 'use_case',
      templateId: 'use_case_page',
      routeFamily: 'use_case',
      contentId: 'use_case_refinance_business_debt',
      title: 'Refinance business debt',
      breadcrumbLabel: 'Refinance business debt',
      footerLabel: 'Refinance business debt',
      panelLabel: 'Refinance business debt',
      panelDescription: 'Refinancing and restructuring existing obligations',
      parentRouteId: 'financing',
      slug: 'refinance-business-debt',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/use-cases/refinance-business-debt'],
    },
    {
      routeId: 'franchise_businesses',
      analyticsRouteId: 'franchise_businesses',
      pageKey: 'franchiseBusinessesIndustry',
      path: '/industries/franchise-businesses',
      pageType: 'industry',
      templateId: 'industry_page',
      routeFamily: 'industry',
      contentId: 'industry_franchise_businesses',
      title: 'Franchise business financing',
      breadcrumbLabel: 'Franchise businesses',
      footerLabel: 'Franchise businesses',
      panelLabel: 'Franchise businesses',
      panelDescription: 'Franchise disclosure, directory, and startup-vs-resale comparisons',
      parentRouteId: 'financing',
      slug: 'franchise-businesses',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/industries/franchise-businesses'],
    },
    {
      routeId: 'trucking_companies',
      analyticsRouteId: 'trucking_companies',
      pageKey: 'truckingCompaniesIndustry',
      path: '/industries/trucking-companies',
      pageType: 'industry',
      templateId: 'industry_page',
      routeFamily: 'industry',
      contentId: 'industry_trucking_companies',
      title: 'Trucking company financing',
      breadcrumbLabel: 'Trucking companies',
      footerLabel: 'Trucking companies',
      panelLabel: 'Trucking companies',
      panelDescription: 'Authority, insurance, tax, and fleet-asset comparisons',
      parentRouteId: 'financing',
      slug: 'trucking-companies',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/industries/trucking-companies'],
    },
    {
      routeId: 'construction_contractors',
      analyticsRouteId: 'construction_contractors',
      pageKey: 'constructionContractorsIndustry',
      path: '/industries/construction-contractors',
      pageType: 'industry',
      templateId: 'industry_page',
      routeFamily: 'industry',
      contentId: 'industry_construction_contractors',
      title: 'Construction contractor financing',
      breadcrumbLabel: 'Construction contractors',
      footerLabel: 'Construction contractors',
      panelLabel: 'Construction contractors',
      panelDescription: 'Work-in-process, bonding, receivables, and equipment comparisons',
      parentRouteId: 'financing',
      slug: 'construction-contractors',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/industries/construction-contractors'],
    },
    {
      routeId: 'california_sba_loans',
      analyticsRouteId: 'california_sba_loans',
      pageKey: 'californiaStatePage',
      path: '/states/california-sba-loans',
      pageType: 'state',
      templateId: 'state_page',
      routeFamily: 'state',
      contentId: 'state_california_sba_loans',
      title: 'California SBA loan resources',
      breadcrumbLabel: 'California',
      footerLabel: 'California SBA loans',
      panelLabel: 'California SBA loans',
      panelDescription: 'Los Angeles and San Francisco district resources plus California advising partners',
      parentRouteId: 'financing',
      slug: 'california-sba-loans',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/states/california-sba-loans'],
    },
    {
      routeId: 'florida_sba_loans',
      analyticsRouteId: 'florida_sba_loans',
      pageKey: 'floridaStatePage',
      path: '/states/florida-sba-loans',
      pageType: 'state',
      templateId: 'state_page',
      routeFamily: 'state',
      contentId: 'state_florida_sba_loans',
      title: 'Florida SBA loan resources',
      breadcrumbLabel: 'Florida',
      footerLabel: 'Florida SBA loans',
      panelLabel: 'Florida SBA loans',
      panelDescription: 'North Florida, South Florida, and statewide advising resources',
      parentRouteId: 'financing',
      slug: 'florida-sba-loans',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/states/florida-sba-loans'],
    },
    {
      routeId: 'new_york_sba_loans',
      analyticsRouteId: 'new_york_sba_loans',
      pageKey: 'newYorkStatePage',
      path: '/states/new-york-sba-loans',
      pageType: 'state',
      templateId: 'state_page',
      routeFamily: 'state',
      contentId: 'state_new_york_sba_loans',
      title: 'New York SBA loan resources',
      breadcrumbLabel: 'New York',
      footerLabel: 'New York SBA loans',
      panelLabel: 'New York SBA loans',
      panelDescription: 'Upstate, New York City, and statewide advising resources',
      parentRouteId: 'financing',
      slug: 'new-york-sba-loans',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/states/new-york-sba-loans'],
    },
    {
      routeId: 'texas_sba_loans',
      analyticsRouteId: 'texas_sba_loans',
      pageKey: 'texasStatePage',
      path: '/states/texas-sba-loans',
      pageType: 'state',
      templateId: 'state_page',
      routeFamily: 'state',
      contentId: 'state_texas_sba_loans',
      title: 'Texas SBA loan resources',
      breadcrumbLabel: 'Texas',
      footerLabel: 'Texas SBA loans',
      panelLabel: 'Texas SBA loans',
      panelDescription: 'Houston, DFW, San Antonio, and El Paso district resources plus Texas advising partners',
      parentRouteId: 'financing',
      slug: 'texas-sba-loans',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/states/texas-sba-loans'],
    },
    {
      routeId: 'houston_sba_loans',
      analyticsRouteId: 'houston_sba_loans',
      pageKey: 'houstonMetroPage',
      path: '/metros/texas/houston-sba-loans',
      pageType: 'metro',
      templateId: 'metro_page',
      routeFamily: 'metro',
      contentId: 'metro_houston_sba_loans',
      title: 'Houston SBA loan resources',
      breadcrumbLabel: 'Houston',
      footerLabel: 'Houston SBA loans',
      panelLabel: 'Houston SBA loans',
      panelDescription: 'SBA Houston District Office and Texas Gulf Coast SBDC resources',
      parentRouteId: 'texas_sba_loans',
      slug: 'texas/houston-sba-loans',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: [],
    },
    {
      routeId: 'san_antonio_sba_loans',
      analyticsRouteId: 'san_antonio_sba_loans',
      pageKey: 'sanAntonioMetroPage',
      path: '/metros/texas/san-antonio-sba-loans',
      pageType: 'metro',
      templateId: 'metro_page',
      routeFamily: 'metro',
      contentId: 'metro_san_antonio_sba_loans',
      title: 'San Antonio SBA loan resources',
      breadcrumbLabel: 'San Antonio',
      footerLabel: 'San Antonio SBA loans',
      panelLabel: 'San Antonio SBA loans',
      panelDescription: 'SBA San Antonio District Office and UTSA SBDC resources',
      parentRouteId: 'texas_sba_loans',
      slug: 'texas/san-antonio-sba-loans',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: [],
    },
    {
      routeId: 'dallas_sba_loans',
      analyticsRouteId: 'dallas_sba_loans',
      pageKey: 'dallasMetroPage',
      path: '/metros/texas/dallas-sba-loans',
      pageType: 'metro',
      templateId: 'metro_page',
      routeFamily: 'metro',
      contentId: 'metro_dallas_sba_loans',
      title: 'Dallas SBA loan resources',
      breadcrumbLabel: 'Dallas',
      footerLabel: 'Dallas SBA loans',
      panelLabel: 'Dallas SBA loans',
      panelDescription: 'SBA DFW District Office and Dallas College SBDC resources',
      parentRouteId: 'texas_sba_loans',
      slug: 'texas/dallas-sba-loans',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: [],
    },
    {
      routeId: 'austin_sba_loans',
      analyticsRouteId: 'austin_sba_loans',
      pageKey: 'austinMetroPage',
      path: '/metros/texas/austin-sba-loans',
      pageType: 'metro',
      templateId: 'metro_page',
      routeFamily: 'metro',
      contentId: 'metro_austin_sba_loans',
      title: 'Austin SBA loan resources',
      breadcrumbLabel: 'Austin',
      footerLabel: 'Austin SBA loans',
      panelLabel: 'Austin SBA loans',
      panelDescription: 'SBA San Antonio District Office and Texas State SBDC resources',
      parentRouteId: 'texas_sba_loans',
      slug: 'texas/austin-sba-loans',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: [],
    },
    {
      routeId: 'fort_worth_sba_loans',
      analyticsRouteId: 'fort_worth_sba_loans',
      pageKey: 'fortWorthMetroPage',
      path: '/metros/texas/fort-worth-sba-loans',
      pageType: 'metro',
      templateId: 'metro_page',
      routeFamily: 'metro',
      contentId: 'metro_fort_worth_sba_loans',
      title: 'Fort Worth SBA loan resources',
      breadcrumbLabel: 'Fort Worth',
      footerLabel: 'Fort Worth SBA loans',
      panelLabel: 'Fort Worth SBA loans',
      panelDescription: 'SBA DFW District Office and TCC SBDC resources',
      parentRouteId: 'texas_sba_loans',
      slug: 'texas/fort-worth-sba-loans',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: [],
    },
    {
      routeId: 'el_paso_sba_loans',
      analyticsRouteId: 'el_paso_sba_loans',
      pageKey: 'elPasoMetroPage',
      path: '/metros/texas/el-paso-sba-loans',
      pageType: 'metro',
      templateId: 'metro_page',
      routeFamily: 'metro',
      contentId: 'metro_el_paso_sba_loans',
      title: 'El Paso SBA loan resources',
      breadcrumbLabel: 'El Paso',
      footerLabel: 'El Paso SBA loans',
      panelLabel: 'El Paso SBA loans',
      panelDescription: 'SBA El Paso District Office and EPCC SBDC resources',
      parentRouteId: 'texas_sba_loans',
      slug: 'texas/el-paso-sba-loans',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: [],
    },
    {
      routeId: 'arlington_sba_loans',
      analyticsRouteId: 'arlington_sba_loans',
      pageKey: 'arlingtonMetroPage',
      path: '/metros/texas/arlington-sba-loans',
      pageType: 'metro',
      templateId: 'metro_page',
      routeFamily: 'metro',
      contentId: 'metro_arlington_sba_loans',
      title: 'Arlington SBA loan resources',
      breadcrumbLabel: 'Arlington',
      footerLabel: 'Arlington SBA loans',
      panelLabel: 'Arlington SBA loans',
      panelDescription: 'SBA DFW District Office and UT Arlington SBDC resources',
      parentRouteId: 'texas_sba_loans',
      slug: 'texas/arlington-sba-loans',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: [],
    },
    {
      routeId: 'corpus_christi_sba_loans',
      analyticsRouteId: 'corpus_christi_sba_loans',
      pageKey: 'corpusChristiMetroPage',
      path: '/metros/texas/corpus-christi-sba-loans',
      pageType: 'metro',
      templateId: 'metro_page',
      routeFamily: 'metro',
      contentId: 'metro_corpus_christi_sba_loans',
      title: 'Corpus Christi SBA loan resources',
      breadcrumbLabel: 'Corpus Christi',
      footerLabel: 'Corpus Christi SBA loans',
      panelLabel: 'Corpus Christi SBA loans',
      panelDescription: 'SBA San Antonio District Office and Del Mar College SBDC resources',
      parentRouteId: 'texas_sba_loans',
      slug: 'texas/corpus-christi-sba-loans',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: [],
    },
    {
      routeId: 'plano_sba_loans',
      analyticsRouteId: 'plano_sba_loans',
      pageKey: 'planoMetroPage',
      path: '/metros/texas/plano-sba-loans',
      pageType: 'metro',
      templateId: 'metro_page',
      routeFamily: 'metro',
      contentId: 'metro_plano_sba_loans',
      title: 'Plano SBA loan resources',
      breadcrumbLabel: 'Plano',
      footerLabel: 'Plano SBA loans',
      panelLabel: 'Plano SBA loans',
      panelDescription: 'SBA DFW District Office and Collin SBDC resources',
      parentRouteId: 'texas_sba_loans',
      slug: 'texas/plano-sba-loans',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: [],
    },
    {
      routeId: 'laredo_sba_loans',
      analyticsRouteId: 'laredo_sba_loans',
      pageKey: 'laredoMetroPage',
      path: '/metros/texas/laredo-sba-loans',
      pageType: 'metro',
      templateId: 'metro_page',
      routeFamily: 'metro',
      contentId: 'metro_laredo_sba_loans',
      title: 'Laredo SBA loan resources',
      breadcrumbLabel: 'Laredo',
      footerLabel: 'Laredo SBA loans',
      panelLabel: 'Laredo SBA loans',
      panelDescription: 'SBA San Antonio District Office and TAMIU SBDC resources',
      parentRouteId: 'texas_sba_loans',
      slug: 'texas/laredo-sba-loans',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: [],
    },
    {
      routeId: 'how_it_works',
      analyticsRouteId: 'how_it_works',
      pageKey: 'howItWorks',
      path: '/how-it-works',
      pageType: 'financing_hub',
      templateId: 'process_page',
      routeFamily: 'conversion_support',
      contentId: 'page_how_it_works',
      title: 'How it works',
      navLabel: 'How it works',
      breadcrumbLabel: 'How it works',
      footerLabel: 'How it works',
      parentRouteId: 'home',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'monthly', priority: '0.7' },
      legacyHashes: ['#/how-it-works'],
    },
    {
      routeId: 'about',
      analyticsRouteId: 'about',
      pageKey: 'about',
      path: '/about',
      pageType: 'financing_hub',
      templateId: 'brand_page',
      routeFamily: 'brand',
      contentId: 'page_about',
      title: 'About Fund44',
      navLabel: 'About',
      breadcrumbLabel: 'About',
      footerLabel: 'About Fund44',
      parentRouteId: 'home',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: false, changefreq: 'monthly', priority: '0.6' },
      legacyHashes: ['#/about'],
    },
    {
      routeId: 'resources',
      analyticsRouteId: 'resources',
      pageKey: 'resources',
      path: '/resources',
      pageType: 'article',
      templateId: 'resources_hub',
      routeFamily: 'resources_hub',
      contentId: 'page_resources',
      title: 'Resources',
      navLabel: 'Resources',
      breadcrumbLabel: 'Resources',
      footerLabel: 'Learning hub',
      parentRouteId: 'home',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: true, changefreq: 'weekly', priority: '0.7' },
      legacyHashes: ['#/resources'],
    },
    {
      routeId: 'resource_sba_7a_vs_504',
      analyticsRouteId: 'resource_sba_7a_vs_504',
      pageKey: 'article',
      path: '/resources/sba-7a-vs-504',
      pageType: 'article',
      templateId: 'editorial_article',
      routeFamily: 'resources_article',
      contentId: 'article_sba_7a_vs_504',
      title: 'SBA 7(a) vs SBA 504',
      breadcrumbLabel: 'SBA 7(a) vs 504',
      footerLabel: 'SBA 7(a) vs 504',
      parentRouteId: 'resources',
      slug: 'sba-7a-vs-504',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: false, landing: true, changefreq: 'monthly', priority: '0.6' },
      legacyHashes: ['#/resources/sba-7a-vs-504'],
    },
    {
      routeId: 'resource_preparing_documents',
      analyticsRouteId: 'resource_preparing_documents',
      pageKey: 'article',
      path: '/resources/preparing-your-documents',
      pageType: 'article',
      templateId: 'editorial_article',
      routeFamily: 'resources_article',
      contentId: 'article_preparing_your_documents',
      title: 'Preparing your documents',
      breadcrumbLabel: 'Preparing your documents',
      parentRouteId: 'resources',
      slug: 'preparing-your-documents',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: false, landing: true, changefreq: 'monthly', priority: '0.6' },
      legacyHashes: ['#/resources/preparing-your-documents'],
    },
    {
      routeId: 'resource_working_capital_vs_term_loan',
      analyticsRouteId: 'resource_working_capital_vs_term_loan',
      pageKey: 'article',
      path: '/resources/working-capital-vs-term-loan',
      pageType: 'article',
      templateId: 'editorial_article',
      routeFamily: 'resources_article',
      contentId: 'article_working_capital_vs_term_loan',
      title: 'Line of credit or term loan?',
      breadcrumbLabel: 'Line of credit or term loan?',
      parentRouteId: 'resources',
      slug: 'working-capital-vs-term-loan',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: false, landing: true, changefreq: 'monthly', priority: '0.6' },
      legacyHashes: ['#/resources/working-capital-vs-term-loan'],
    },
    {
      routeId: 'privacy',
      analyticsRouteId: 'privacy',
      pageKey: 'privacy',
      path: '/privacy',
      pageType: 'legal',
      templateId: 'legal_page',
      routeFamily: 'legal',
      contentId: 'page_privacy',
      title: 'Privacy',
      breadcrumbLabel: 'Privacy',
      footerLabel: 'Privacy',
      parentRouteId: 'home',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: false, changefreq: 'yearly', priority: '0.3' },
      legacyHashes: ['#/privacy'],
    },
    {
      routeId: 'terms',
      analyticsRouteId: 'terms',
      pageKey: 'terms',
      path: '/terms',
      pageType: 'legal',
      templateId: 'legal_page',
      routeFamily: 'legal',
      contentId: 'page_terms',
      title: 'Terms & disclosures',
      breadcrumbLabel: 'Terms & disclosures',
      footerLabel: 'Terms & disclosures',
      parentRouteId: 'home',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: false, changefreq: 'yearly', priority: '0.3' },
      legacyHashes: ['#/terms'],
    },
    {
      routeId: 'contact',
      analyticsRouteId: 'contact',
      pageKey: 'contact',
      path: '/contact',
      pageType: 'contact',
      templateId: 'contact_page',
      routeFamily: 'contact',
      contentId: 'page_contact',
      title: 'Contact',
      breadcrumbLabel: 'Contact',
      footerLabel: 'Contact',
      parentRouteId: 'home',
      crawl: { canonical: true, indexable: true, sitemap: true, llms: true, landing: false, changefreq: 'yearly', priority: '0.3' },
      legacyHashes: ['#/contact'],
    },
    {
      routeId: 'not_found',
      analyticsRouteId: 'not_found',
      pageKey: 'notFound',
      path: '/404',
      pageType: '404',
      templateId: '404_page',
      routeFamily: 'error',
      contentId: 'page_404',
      title: 'Page not found',
      breadcrumbLabel: 'Not found',
      crawl: { canonical: false, indexable: false, sitemap: false, llms: false, landing: false, changefreq: 'never', priority: '0.0' },
      legacyHashes: [],
    },
  ],
  navigation: {
    primary: [
      {
        routeId: 'financing',
        label: 'Financing',
        panel: ['financing', 'sba_7a', 'sba_504', 'business_acquisition', 'working_capital', 'term_loan', 'line_of_credit', 'equipment_financing', 'buy_a_business', 'owner_occupied_real_estate', 'cash_flow_needs', 'equipment_purchase', 'business_expansion', 'refinance_business_debt', 'franchise_businesses', 'trucking_companies', 'construction_contractors', 'california_sba_loans', 'florida_sba_loans', 'new_york_sba_loans', 'texas_sba_loans', 'houston_sba_loans', 'san_antonio_sba_loans', 'dallas_sba_loans', 'austin_sba_loans', 'fort_worth_sba_loans', 'el_paso_sba_loans', 'arlington_sba_loans', 'corpus_christi_sba_loans', 'plano_sba_loans', 'laredo_sba_loans'],
      },
      { routeId: 'how_it_works', label: 'How it works' },
      { routeId: 'resources', label: 'Resources' },
      { routeId: 'about', label: 'About' },
    ],
    mobile: [
      { routeId: 'home', label: 'Home' },
      { routeId: 'financing', label: 'Financing' },
      { routeId: 'sba_7a', label: 'SBA 7(a) loans', className: 'sub' },
      { routeId: 'sba_504', label: 'SBA 504 loans', className: 'sub' },
      { routeId: 'business_acquisition', label: 'Business acquisition', className: 'sub' },
      { routeId: 'working_capital', label: 'Working capital & lines', className: 'sub' },
      { routeId: 'term_loan', label: 'Business term loans', className: 'sub' },
      { routeId: 'line_of_credit', label: 'Business lines of credit', className: 'sub' },
      { routeId: 'equipment_financing', label: 'Equipment financing', className: 'sub' },
      { routeId: 'buy_a_business', label: 'Buy a business', className: 'sub' },
      { routeId: 'owner_occupied_real_estate', label: 'Owner-occupied real estate', className: 'sub' },
      { routeId: 'cash_flow_needs', label: 'Cash-flow needs', className: 'sub' },
      { routeId: 'equipment_purchase', label: 'Equipment purchase', className: 'sub' },
      { routeId: 'business_expansion', label: 'Business expansion', className: 'sub' },
      { routeId: 'refinance_business_debt', label: 'Refinance business debt', className: 'sub' },
      { routeId: 'franchise_businesses', label: 'Franchise businesses', className: 'sub' },
      { routeId: 'trucking_companies', label: 'Trucking companies', className: 'sub' },
      { routeId: 'construction_contractors', label: 'Construction contractors', className: 'sub' },
      { routeId: 'california_sba_loans', label: 'California SBA loans', className: 'sub' },
      { routeId: 'florida_sba_loans', label: 'Florida SBA loans', className: 'sub' },
      { routeId: 'new_york_sba_loans', label: 'New York SBA loans', className: 'sub' },
      { routeId: 'texas_sba_loans', label: 'Texas SBA loans', className: 'sub' },
      { routeId: 'houston_sba_loans', label: 'Houston SBA loans', className: 'sub' },
      { routeId: 'san_antonio_sba_loans', label: 'San Antonio SBA loans', className: 'sub' },
      { routeId: 'dallas_sba_loans', label: 'Dallas SBA loans', className: 'sub' },
      { routeId: 'austin_sba_loans', label: 'Austin SBA loans', className: 'sub' },
      { routeId: 'fort_worth_sba_loans', label: 'Fort Worth SBA loans', className: 'sub' },
      { routeId: 'el_paso_sba_loans', label: 'El Paso SBA loans', className: 'sub' },
      { routeId: 'arlington_sba_loans', label: 'Arlington SBA loans', className: 'sub' },
      { routeId: 'corpus_christi_sba_loans', label: 'Corpus Christi SBA loans', className: 'sub' },
      { routeId: 'plano_sba_loans', label: 'Plano SBA loans', className: 'sub' },
      { routeId: 'laredo_sba_loans', label: 'Laredo SBA loans', className: 'sub' },
      { routeId: 'how_it_works', label: 'How it works' },
      { routeId: 'resources', label: 'Resources' },
      { routeId: 'about', label: 'About' },
    ],
    footer: [
      { heading: 'Financing', items: ['sba_7a', 'sba_504', 'business_acquisition', 'working_capital', 'term_loan', 'line_of_credit', 'equipment_financing', 'buy_a_business', 'owner_occupied_real_estate', 'cash_flow_needs', 'equipment_purchase', 'business_expansion', 'refinance_business_debt', 'franchise_businesses', 'trucking_companies', 'construction_contractors', 'california_sba_loans', 'florida_sba_loans', 'new_york_sba_loans', 'texas_sba_loans', 'houston_sba_loans', 'san_antonio_sba_loans', 'dallas_sba_loans', 'austin_sba_loans', 'fort_worth_sba_loans', 'el_paso_sba_loans', 'arlington_sba_loans', 'corpus_christi_sba_loans', 'plano_sba_loans', 'laredo_sba_loans', 'financing'] },
      { heading: 'Company', items: ['how_it_works', 'about', 'resources', 'resource_sba_7a_vs_504'] },
      { heading: 'Legal', items: ['privacy', 'terms', 'contact'] },
    ],
  },
  ctaDestinations: {
    explore_financing: { routeId: 'financing' },
    learn_how_it_works: { routeId: 'how_it_works' },
    back_home: { routeId: 'home' },
  },
};
